version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - inter-service-network

  redis:
    image: redis
    container_name: redisio
    restart: always
    ports:
      - "6379:6379"
    networks:
      - inter-service-network

  # 5 separate backend containers
  backend1:
    build:
      context: ./server
    container_name: backend1
    expose:
      - "3030"
    networks:
      - inter-service-network
    depends_on:
      - mongo
      - redis

  backend2:
    build:
      context: ./server
    container_name: backend2
    expose:
      - "3030"
    networks:
      - inter-service-network
    depends_on:
      - mongo
      - redis

  backend3:
    build:
      context: ./server
    container_name: backend3
    expose:
      - "3030"
    networks:
      - inter-service-network
    depends_on:
      - mongo
      - redis

  backend4:
    build:
      context: ./server
    container_name: backend4
    expose:
      - "3030"
    networks:
      - inter-service-network
    depends_on:
      - mongo
      - redis

  backend5:
    build:
      context: ./server
    container_name: backend5
    expose:
      - "3030"
    networks:
      - inter-service-network
    depends_on:
      - mongo
      - redis

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
      - backend5
    networks:
      - inter-service-network

networks:
  inter-service-network:
