services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - inter-service-network

  redis:
    image: redis
    container_name: redisio
    restart: always
    ports:
      - "6379:6379"
    networks:
      - inter-service-network

  server:
    build:
      context: ./server
    networks:
      - inter-service-network
    depends_on:
      - mongo
      - redis
    deploy:
      replicas: 15
    expose: 
      - "3030"
    restart: always
    

  nginx_1:
    build:
      context: ./nginx
    container_name: nginx_1
    ports:
      - "1900:8080"
    depends_on: 
      - server
    networks:
      - inter-service-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  nginx_2:
    build:
      context: ./nginx
    container_name: nginx_2
    ports:
      - "1901:8080"
    depends_on: 
      - server
    networks:
      - inter-service-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - nginx_1
      - nginx_2
    networks:
      - inter-service-network

networks:
  inter-service-network: