services:
  server_1:
    build:
      context: ./server
    container_name: server_1
    restart: always
    expose:
      - "3030"
    depends_on:
      - mongo
      - redis
    networks:
      - inter-service-network

  server_2:
    build:
      context: ./server
    container_name: server_2
    restart: always
    expose:
      - "3030"
    depends_on:
      - mongo
      - redis
    networks:
      - inter-service-network

  server_3:
    build:
      context: ./server
    container_name: server_3
    restart: always
    expose:
      - "3030"
    depends_on:
      - mongo
      - redis
    networks:
      - inter-service-network

  server_4:
    build:
      context: ./server
    container_name: server_4
    restart: always
    expose:
      - "3030"
    depends_on:
      - mongo
      - redis
    networks:
      - inter-service-network


  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - inter-service-network

  redis:
    image: redis
    container_name: redisio
    restart: always
    ports:
      - "6379:6379"
    networks:
      - inter-service-network

  # can we do this duplication above manually?

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - server_1
      - server_2
      - server_3
      - server_4
    networks:
      - inter-service-network

networks:
  inter-service-network:
